export enum PricingTypes {
    STANDARD_MONTHLY = "STANDARD_MONTHLY",
    STANDARD_YEARLY = "STANDARD_YEARLY",
    EVOLUTION_MONTHLY = "EVOLUTION_MONTHLY",
    EVOLUTION_YEARLY = "EVOLUTION_YEARLY",
}
